//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.BankA {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ordem", Namespace="http://schemas.datacontract.org/2004/07/BankA")]
    [System.SerializableAttribute()]
    public partial class Ordem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int clientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int companyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string creationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string executionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float valueStockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int clientId {
            get {
                return this.clientIdField;
            }
            set {
                if ((this.clientIdField.Equals(value) != true)) {
                    this.clientIdField = value;
                    this.RaisePropertyChanged("clientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int companyId {
            get {
                return this.companyIdField;
            }
            set {
                if ((this.companyIdField.Equals(value) != true)) {
                    this.companyIdField = value;
                    this.RaisePropertyChanged("companyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string creationDate {
            get {
                return this.creationDateField;
            }
            set {
                if ((object.ReferenceEquals(this.creationDateField, value) != true)) {
                    this.creationDateField = value;
                    this.RaisePropertyChanged("creationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string executionDate {
            get {
                return this.executionDateField;
            }
            set {
                if ((object.ReferenceEquals(this.executionDateField, value) != true)) {
                    this.executionDateField = value;
                    this.RaisePropertyChanged("executionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quant {
            get {
                return this.quantField;
            }
            set {
                if ((this.quantField.Equals(value) != true)) {
                    this.quantField = value;
                    this.RaisePropertyChanged("quant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int state {
            get {
                return this.stateField;
            }
            set {
                if ((this.stateField.Equals(value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float valueStock {
            get {
                return this.valueStockField;
            }
            set {
                if ((this.valueStockField.Equals(value) != true)) {
                    this.valueStockField = value;
                    this.RaisePropertyChanged("valueStock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankA.IBankAOps", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IBankAOps {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankAOps/Deposit", ReplyAction="http://tempuri.org/IBankAOps/DepositResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        void Deposit(int acct, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankAOps/Withdraw", ReplyAction="http://tempuri.org/IBankAOps/WithdrawResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        void Withdraw(int acct, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankAOps/GetBalance", ReplyAction="http://tempuri.org/IBankAOps/GetBalanceResponse")]
        double GetBalance(int acct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankAOps/GetOrdens", ReplyAction="http://tempuri.org/IBankAOps/GetOrdensResponse")]
        Client.BankA.Ordem[] GetOrdens();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankAOpsChannel : Client.BankA.IBankAOps, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankAOpsClient : System.ServiceModel.ClientBase<Client.BankA.IBankAOps>, Client.BankA.IBankAOps {
        
        public BankAOpsClient() {
        }
        
        public BankAOpsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankAOpsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankAOpsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankAOpsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Deposit(int acct, double amount) {
            base.Channel.Deposit(acct, amount);
        }
        
        public void Withdraw(int acct, double amount) {
            base.Channel.Withdraw(acct, amount);
        }
        
        public double GetBalance(int acct) {
            return base.Channel.GetBalance(acct);
        }
        
        public Client.BankA.Ordem[] GetOrdens() {
            return base.Channel.GetOrdens();
        }
    }
}
